<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Phalcon Console</title>
		<meta name="viewport" content="width=device-width">

        <link rel="stylesheet" href="/console/css/normalize.css"/>
        <link rel="stylesheet" href="/console/css/main.css"/>
        <link rel="stylesheet" href="/console/css/codemirror.css"/>
        <link rel="stylesheet" href="/console/css/laravel.css"/>

        <script type="text/javascript" src="/console/js/vendor/modernizr.js"></script>
	</head>
	<body>